apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shadecn-learning
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - demo.fyl080801.uk
      secretName: shadecn-learning-tls
  rules:
    - host: demo.fyl080801.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shadecn-learning
                port:
                  number: 80